# Base configs
baseurl: "https://photography.rampatra.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Yesh's Photography"
subtitle: "Visualizing the world to capture"
author: "Yeshwanth Reddy"
header:
 title: "Photography"
 subtitle: "by Yeshwanth"
footer:
 name: "Hello, this is Yeshwanth"
 bio: "I am an undergrad student working in Data Science domain."
 github: "You can look at my blog on articles related to Data Science, here, <a href=\"https://neulearn.github.io\">Neulearn</a>."
web_design: "AJ"
social_urls:
  #facebook: "https://www.facebook.com/ramswaroop"
  twitter: "https://www.twitter.com/yeshuu16"
  instagram: "https://www.instagram.com/yeshwanth_reddy16"
  #dribbble: "https://dribbble.com/rampatra"
  #linkedin: "https://in.linkedin.com/in/ram-patra"
  github: "https://www.github.com/yeshwanth16"
